const root = document.querySelector('[data-page]');
const page = root?.dataset.page || 'home';
const localBase = document.querySelector('meta[name="site-base"]')?.content || '';
const base = location.hostname.endsWith('github.io') ? '/ledportfolio' : localBase;
const href = (path) => `${base}${path}`;

const projects = [
  { title: 'Workflow Optimization for Staffing Firm (Beech Valley)', role: 'Beech Valley Solutions | Principal Product Designer', body: 'Transforming manual processes into an integrated, efficient digital system through in-depth workflow audits and iterative design.', image: 'beech-home.png', workImage: 'bv-applicants.png', link: '/bv-case-study/' },
  { title: 'Scalable UX for Enterprise SaaS (Citrix)', role: 'Citrix | UX Design Lead / Manager', body: 'Designing with a large-scale research program to improve usability for cloud product users across varied environments.', image: 'citrix-home.png', workImage: 'citrix-dashboard.png', link: '/citrix-case-study/' },
  { title: 'Rapid Iteration with Customer Insights (Pendo)', body: 'Using interviews and usability studies to overhaul guide editing, balancing power for technical users with simplicity for others.', image: 'pendo-home.png', link: '/media/Pendo-CaseStudy.pdf' },
  { title: 'Research-Driven Design Systems (Rackspace)', body: 'From 60-foot mental model diagrams to a sustainable UI library adopted across the company.', image: 'rackspace-home.png', link: '/media/Rackspace-CaseStudy.pdf' }
];

const caseStudies = {
  beech: {
    title: 'Workflow Optimization for Staffing Firm',
    role: 'Beech Valley Solutions | Lead Product Designer | Apr 2020 – Jun 2023',
    intro: 'Transformed a small staffing firm’s manual, spreadsheet-heavy processes into a streamlined digital system. Conducted workflow audits, mapped bottlenecks, and designed custom tools to reduce repetitive tasks, improve data accuracy, and free the team to focus on high-value client relationships.',
    sections: [
      ['1. Context & Challenge', ['Beech Valley is a boutique staffing firm specializing in connecting highly skilled finance professionals with contract work. Their growth was hindered by manual, repetitive workflows — from tracking candidate availability in spreadsheets to emailing updates back and forth with clients.', 'These inefficiencies caused delays in placements, introduced errors in candidate data, and created frustration for both staff and clients. The challenge: design internal tools to modernize operations without disrupting ongoing business.'], 'bv-spreadsheet.png'],
      ['2. My Role', ['As Principal Product Designer, I was responsible for:'], null, ['Conducting research into internal workflows and pain points', 'Translating findings into product requirements in collaboration with the business owners', 'Designing, prototyping, and refining internal applications with the engineering team', 'Validating concepts and releases with the end users — the staffing team']],
      ['3. Research & Discovery', ['Methods used:'], 'bv-brief.png', ['Workflow audits: shadowed recruiters and coordinators through their daily tasks', 'Stakeholder interviews: gathered input from leadership on business priorities and constraints', 'Pain-point mapping: created a visual map of bottlenecks and repetitive steps', 'Task time tracking: measured baseline times for key activities to track improvement post-launch']],
      ['4. Design & Iteration', ['Created low-fidelity workflow diagrams to visualize the redesigned process. Designed searchable candidate profiles with real-time availability updates, integrated task dashboards that reduced context switching, and automation for repetitive notifications and follow-ups.'], 'bv-flow.png'],
      ['5. Outcomes & Impact', ['Reduced candidate profile update time by about 50%, improved data accuracy, and freed recruiters to spend more time on relationship building. The work also created a foundation for future feature expansion without re-architecting the core system.'], 'bv-pipeline.png'],
      ['6. Reflection & Relevance', ['This project reinforced how targeted process improvements — through direct observation and iterative design — can significantly improve efficiency in complex workflows. The skills mirror the approach I’d bring to healthcare environments: understanding the human side of operations, designing around real-world constraints, and making daily work smoother and more effective.'], 'bv-client-flow.png']
    ]
  },
  citrix: {
    title: 'Scalable UX for Enterprise SaaS',
    role: 'Citrix | UX Design Lead / Manager | Jul 2017 – Aug 2019',
    intro: 'Led a design team in overhauling Citrix’s flagship cloud product, working alongside a dedicated UX research team to conduct statistically significant usability studies. Balanced enterprise complexity with intuitive workflows, ensuring both technical and non-technical users could navigate and succeed.',
    sections: [
      ['1. Context & Challenge', ['Citrix provides enterprise-level cloud services to a global customer base with varied needs and technical skill levels. Over time, the flagship cloud product became fragmented — with inconsistent patterns, buried functionality, and workflows that were efficient for some users but confusing for others.', 'The challenge: redesign the experience to improve usability and consistency without disrupting customers managing critical, ongoing workloads.'], 'citrix-storefront.jpg'],
      ['2. My Role', ['As UX Design Lead & Design Manager, I was responsible for:'], null, ['Setting the design vision for the cloud product overhaul', 'Collaborating with the UX research team to design and interpret large-scale studies', 'Managing and mentoring a team of designers', 'Partnering with Product Management and Engineering to align priorities and phased delivery']],
      ['3. Research & Discovery', ['Methods used: statistically significant usability studies, task-success and time-on-task analysis, heuristic evaluations, and competitive benchmarking.'], 'citrix-feedback.png'],
      ['4. Design & Iteration', ['Integrated legacy systems with a newly acquired startup’s micro-app functionality, introduced progressive disclosure, and established core navigation and interaction patterns to unify workflows across cloud products.'], 'citrix-architecture.png'],
      ['5. Outcomes & Impact', ['Improved task success rates in follow-up usability studies; the unified platform reduced context switching and frustration, while design-system adoption improved consistency and reduced rework.'], 'citrix-dashboard.png'],
      ['6. Reflection & Relevance', ['This work reinforced the value of combining rigorous research with careful iteration in complex enterprise environments. Unifying workflows for diverse users while ensuring stability during change is directly relevant to multi-role healthcare teams.'], 'citrix-flow.png']
    ]
  }
};

function header() {
  const links = [['/work/', 'Work'], ['/about/', 'About'], ['/contact/', 'Contact'], ['/media/Lauren-Puckett-Resume-2026.pdf', 'Resume']];
  return `<header class="site-header"><a class="brand" href="${href('/')}">Lauren Puckett Portfolio</a><nav class="nav" aria-label="Main navigation">${links.map(([url, label]) => `<a href="${href(url)}"${location.pathname.includes(url.replace(/\/$/, '')) ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav></header>`;
}
function footer() { return `<footer class="footer"><p><a href="mailto:ledpuckett@gmail.com">ledpuckett@gmail.com</a><br><a href="tel:+15405562111">(540) 556-2111</a></p><p class="meta">Lauren Puckett<br>Roanoke, VA</p></footer>`; }
function projectCard(project) { return `<article class="project"><img src="${href(`/media/${project.image}`)}" alt=""><h2>${project.title}</h2><p>${project.body}</p><a class="button" href="${href(project.link)}">Read Case Study <span aria-hidden="true">→</span></a></article>`; }
function showcase(project) { return `<article class="showcase"><img src="${href(`/media/${project.workImage || project.image}`)}" alt=""><div class="showcase-copy"><h2>${project.title}</h2>${project.role ? `<p class="project-role">${project.role}</p>` : ''}<p>${project.body}</p><a class="button" href="${href(project.link)}">[Read Case Study →]</a></div></article>`; }

function home() { return `<section class="hero"><h1>Designing systems and services that work for the people who use them.</h1></section><section class="section section--sand"><div class="split"><p>Intro</p><p>I’m Lauren Puckett — a human-centered design leader with 15+ years of experience turning complex workflows into clear, intuitive experiences. For nearly a decade, I’ve been drawn to healthcare experience design, and I’m now focused on bringing my research, service design, and collaboration skills into this field.</p></div></section><section class="section section--sand"><div class="split"><p>What I Do</p><div class="stack"><p><strong>Research & Discovery</strong> — Usability testing, user interviews, workflow analysis, contextual inquiry</p><p><strong>Design & Strategy</strong> — Service design, interaction design, prototyping</p><p><strong>Collaboration</strong> — Partnering with cross-disciplinary teams to deliver measurable improvements</p></div></div></section><section class="section"><p class="eyebrow">Relevant Case Studies</p><div class="carousel"><div class="carousel-track">${projects.map(projectCard).join('')}</div><div class="carousel-controls"><button type="button" data-scroll="-1" aria-label="Previous case study">←</button><button type="button" data-scroll="1" aria-label="Next case study">→</button></div></div></section><section class="section section--sand"><div class="split"><p>My Approach</p><div class="stack"><p><strong>Understand the People & Context</strong> — Research methods tailored to the environment</p><p><strong>Design for Real-World Use</strong> — Systems thinking and attention to details that matter</p><p><strong>Iterate & Measure</strong> — Refining based on feedback and measurable impact</p></div></div></section><section class="section"><div class="split"><p>Why Healthcare Now</p><p>For years, I’ve been inspired by the potential of design to improve healthcare — not only in digital tools but also in physical environments and service touchpoints. My experience optimizing complex systems, conducting usability testing, and collaborating across disciplines has prepared me to contribute meaningfully in this space.</p></div></section><section class="section section--sand"><h2 class="display">Get in Touch.</h2></section>`; }
function work() { return `<section class="work-page section--sand"><h1 class="work-title">Relevant Case Studies</h1><div class="work-list">${projects.map(showcase).join('')}</div></section>`; }
function about() { return `<section class="about-page section--sand"><h1 class="about-title">About Me</h1><div class="about-layout"><div class="about-copy"><h2>Hi, I’m Lauren.</h2><p>I’m a human-centered design leader with 15+ years of experience creating intuitive, efficient, and impactful experiences across SaaS, enterprise, and startup environments. My work spans the full UX spectrum — from research and discovery through design, delivery, and adoption — always with a focus on making complex systems work better for the people who rely on them.</p><p>I’ve led projects that:</p><ul><li>Streamlined operational workflows for small, fast-moving teams</li><li>Unified fragmented enterprise product suites under consistent design systems</li><li>Balanced the needs of both highly technical users and those new to a platform</li><li>Applied Service Design thinking to physical spaces and community engagement</li></ul><p>I’m now intentionally moving toward healthcare, bringing my background in human-centered design, workflow optimization, and cross-disciplinary collaboration to opportunities where it can have a direct and meaningful impact.</p></div><img class="portrait" src="${href('/media/portrait.jpg')}" alt="Lauren Puckett smiling outdoors"></div></section>`; }
function contact() { return `<section class="contact-page"><img src="${href('/media/books.jpg')}" alt="A stack of books on design, UX, and startup topics"><div class="contact-card"><h1>Let’s talk.</h1><a href="mailto:ledpuckett@gmail.com">ledpuckett@gmail.com</a><a href="tel:+15405562111">(540) 556-2111</a><p><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a></p><p><a href="https://www.behance.net" target="_blank" rel="noreferrer">Behance</a></p></div></section>`; }
function study(study) { return `<section class="case-hero"><h1 class="display">${study.title}</h1><p class="case-role">${study.role}</p><p>${study.intro}</p></section>${study.sections.map(([title, paragraphs, image, bullets]) => `<section class="case-section"><h2>${title}</h2><div><div class="stack">${paragraphs.map(p => `<p>${p}</p>`).join('')}${bullets ? `<ul>${bullets.map(item => `<li>${item}</li>`).join('')}</ul>` : ''}</div>${image ? `<img class="case-image" src="${href(`/media/${image}`)}" alt="">` : ''}</div></section>`).join('')}`; }

const views = { home, work, about, contact, beech: () => study(caseStudies.beech), citrix: () => study(caseStudies.citrix) };
document.title = `${page === 'home' ? 'Lauren Puckett Portfolio' : page[0].toUpperCase() + page.slice(1)} — Lauren Puckett Portfolio`;
root.innerHTML = `${header()}<main class="page">${views[page] ? views[page]() : home()}</main>${footer()}`;
document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => button.closest('.carousel').querySelector('.carousel-track').scrollBy({ left: Number(button.dataset.scroll) * 420, behavior: 'smooth' })));
